config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

    validates :password, presence: true, length: { minimum: 6 }

    before_save { self.email = email.downcase }

    before_create { self.sign_in_count = 1 }

    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      sign_in_count(user)
      redirect_to root_url
      flash[:notice] = 'Signed In'
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "Signed Up"
      redirect_to root_url
    else
      flash.now[:alert] = "Invalid Form"
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def sign_in_count(user)
    user.increment!(:sign_in_count)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginCount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id="header">
    
    <div id="home-link"><%= link_to "Home", root_url %></div>

    <% if logged_in? %>
      <span id="logout-link"><%= link_to "Log out", logout_path, method: "delete" %></span> 
      <span id="logged-in-link">Logged In As: <%= current_user.name %> </span>
    <% else %>
      <span id="login-link"><%= link_to "Log in", login_path %></span>
      <span id="signup-link"><%= link_to "Sign Up", new_user_path %></span>
    <% end %>

  </header>

  <% if flash[:notice]%>
    <div><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:alert]%>
    <div><%= flash[:alert] %></div>
  <% end %>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1 id="form-heading">All Users</h1>

<table id="table-container" border="1">

    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Sign In Count</th>
    </tr>
  
  <% @users.each do |user| %>

  <tr>

    <td align="center">
      <%= user.name %>
    </td>

    <td align="center">
      <%= user.email %>
    </td>

    <td align="center">
    <%= user.sign_in_count %>
    </td>

  </tr>

  <% end %>

</table>

app/views/users/new.html.erb
<h1 id="form-heading">Sign up</h1>

  <%= form_for(@user) do |f| %>
    
    <div id="form-container">
        <span id="form-label"><%= f.label :name %>:</span><br />
        <span id="form-label"><%= f.text_field :name %></span><br />
        
        <span id="form-label"><%= f.label :email %>:</span><br />
        <span id="form-label"><%= f.email_field :email %></span><br />
        
        <span id="form-label"><%= f.label :password %>:</span><br />
        <span id="form-label"><%= f.password_field :password %></span><br />
        
        <span id="form-label"><%= f.label :password_confirmation, "Confirmation" %>:</span><br />
        <span id="form-label"><%= f.password_field :password_confirmation %></span><br />
    
    <%= f.submit "Sign Up" %>
    </div>

  <% end %>